import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { ReactNode } from "react";
import Header from "@/layouts/Header";

interface Props {
  children: ReactNode;
}

export default function DefaultLayout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={`${styles.main}`}>{children}</main>
    </>
  );
}
